M48
; DRILL file {KiCad (6.0.7-1)-1} date Samstag, 20. August 2022 um 21:08:40
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-08-20T21:08:40+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7-1)-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
%
G90
G05
T1
X103.5Y-55.5
X103.5Y-79.0
X167.0Y-79.0
X167.2Y-55.4
T2
X145.34Y-63.2
T0
M30
